version: 0.0
os: linux 
files:
  - source: /
    destination: /home/backend  
hooks:
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/after.sh
      timeout: 300
      runas: root